### ISSUE TITLE
How to properly handle errors in nuxt ?

### ISSUE THREAD

**Issue by golubvladimir** [ivanmarban/winston-telegram#15]
I have winston configuration with telegram.

```
const logger = winston.createLogger({
  format: winston.format.json(),
  transports: [
    new TelegramLogger({
      token: '...',
      chatId: '...',
      level: 'info',
      unique: true
    }),
    new TelegramLogger({
      token: '...',
      chatId: '...',
      level: 'error',
      unique: true
    })
  ]
});
```
Function send message

```
const sendToTelegram = function send(level, message) {
  logger.log({
    level: level,
    message: message
  });
};
```

Route for logger
```
router.post('/logger', async (req, res) => {
  try {
    if (['info', 'error'].indexOf(req.body.level) !== -1 && req.body.token === '...') {
      const dateLog = new Date();
      await sendToTelegram(
          req.body.level,
          `
            ${dateLog.getHours()}:${dateLog.getMinutes()}:${dateLog.getSeconds()}
            ${dateLog.getDay()}.${dateLog.getMonth()}.${dateLog.getFullYear()}
            ${req.body.message}
          `
          .replace(/\r?\n/g, "")
          .replace(/\s{2,}/g, ' ')
      );
      res.status(200).json({status: 'ok'});
   } catch(e) {
      const err = {
        info: e
      };
      res.status(500).json(err);
   }
}
```

After sending the request with Postman, i getting message "status": "ok".
But after a few seconds in the console I see an error:
`Error: connect ETIMEDOUT 149.154.167.220:443`
`[nodemon] app crashed - waiting for file changes before starting...`

 How to properly handle errors ?

**Comment by ivanmarban** [comment]
Are you receiving those messages in your Telegram chat or the application is crashing before the message is posted to Telegram API ? That error is a timeout of the Telegram API...

Winston has his own mechanism to handle uncaught exceptions. You only need to enable your logger instance with this behaviour, have you tried that ?

[Handling Uncaught Exceptions with winston](https://github.com/winstonjs/winston#handling-uncaught-exceptions-with-winston)

**Comment by golubvladimir** [comment]
@ivanmarban 
I changed the configuration
```
const {createLogger, transports, format} = require('winston');
const TelegramLogger = require('winston-telegram');

const logger = createLogger({
  format: format.json(),
  transports: [
    new TelegramLogger({
      token: '***',
      chatId: '***',
      level: 'info',
      unique: true
    }),
    new TelegramLogger({
      token: '***',
      chatId: '***',
      level: 'error',
      unique: true
    })
  ],
  exceptionHandlers: [
    new transports.File({ filename: 'exceptions.log' })
  ]
});
```

Now I do not see errors in the console.
The problem with nodemon persisted

**Comment by ivanmarban** [comment]
What do you see at exceptions.log ?

**Comment by golubvladimir** [comment]
@ivanmarban
```
{
"error":
{
"errno":"ETIMEDOUT",
"code":"ETIMEDOUT",
"syscall":"connect",
"address":"149.154.167.220",
"port":443
},
"level":"error",
"message":"uncaughtException: connect ETIMEDOUT 149.154.167.220:443\nError: connect ETIMEDOUT 149.154.167.220:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)",
"stack":"Error: connect ETIMEDOUT 149.154.167.220:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)",
"exception":true,
"date":"Fri Dec 06 2019 11:42:34 GMT+0200 (GMT+02:00)",
"process":
{"pid":13280,
"uid":null,
"gid":null,
"cwd":"...",
"execPath":"C:\\Program Files\\nodejs\\node.exe",
"version":"v12.13.1",
"argv":["C:\\Program Files\\nodejs\\node.exe","...\\server\\index.js"],
"memoryUsage":{"rss":443121664,"heapTotal":246632448,"heapUsed":221938448,"external":135352438}},"os":{"loadavg":[0,0,0],"uptime":7040},"trace":[{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1129,"method":"afterConnect [as oncomplete]","native":false}]}
```
Telegram is blocked in my country.

**Comment by ivanmarban** [comment]
> Telegram is blocked in my country.

That's the problem then.

**Comment by golubvladimir** [comment]
@ivanmarban 
How to handle such errors without rebooting the server ?

**Comment by ivanmarban** [comment]
I guess that is a topic related with nodemon. I'm not familiar about nodemon but to me seems that is adding his own listeners to uncaught exceptions and handling them in his way.
