### ISSUE TITLE
429: Too Many Requests: retry after 5

### ISSUE THREAD

**Issue by takahser** [ivanmarban/winston-telegram#21]
When sending many request during a certain timeframe, the Telegram API reacts with a HTTP 429 Error code (too many requests):

```
events.js:306
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('429: Too Many Requests: retry after 5')
    at DerivedLogger.emit (events.js:304:17)
    at DerivedLogger.transportEvent (/usr/src/app/node_modules/winston/lib/winston/logger.js:630:12)
    at Telegram.emit (events.js:327:22)
    at /usr/src/app/node_modules/winston-telegram/lib/winston-telegram.js:133:14
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/winston-telegram/lib/winston-telegram.js:155:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_UNHANDLED_ERROR',
  context: '429: Too Many Requests: retry after 5'
}
```

Is there a recommended way to handle rate limiting issues?

**Comment by ivanmarban** [comment]
Take a look at _batchingDelay_ parameter.

https://github.com/ivanmarban/winston-telegram/blob/master/examples/batching-messages.js

https://github.com/ivanmarban/winston-telegram/pull/8
