### ISSUE TITLE
    this.handleExceptions = options.handleExceptions ?? true 

### ISSUE THREAD

**Issue by mawenchao** [ivanmarban/winston-telegram#37]
> crypto-trading-bot@0.0.0 start /usr/src/app
> node index.js trade

/usr/src/app/node_modules/winston-telegram/lib/winston-telegram.js:46
    this.handleExceptions = options.handleExceptions ?? true
                                                      ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/modules/services.js:46:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-09T03_06_21_437Z-debug.log

**Comment by ivanmarban** [comment]
What version of node.js are you using? This is only supported in v14+

https://github.com/ivanmarban/winston-telegram/blob/6d903eb0db39c2205f548e20ee14fca1e3667022/package.json#L29
